[font]
size = 19.0
normal.family = "JetBrainsMono Nerd Font"
offset.y = 2


[window]
decorations = "none"
padding.x = 20
padding.y = 30
dynamic_padding = true
startup_mode = "SimpleFullscreen"

[colors]
primary.background = '#000000'
selection = { text = "CellForeground", background = "#2aa198" }

# Normal colors
[colors.normal]
black   = '#073642'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#d33682'
cyan    = '#2aa198'
white   = '#eee8d5'

# Bright colors
[colors.bright]
black   = '#4c4c4c'
red     = '#cb4b16'
green   = '#586e75'
yellow  = '#657b83'
blue    = '#839496'
magenta = '#6c71c4'
cyan    = '#93a1a1'
white   = '#fdf6e3'

[mouse]
hide_when_typing = true



[selection]
save_to_clipboard = true
